name: price_list
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.2.0


dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.1.3
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  http: ^1.3.0
  sqflite_sqlcipher: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  mockito: ^5.5.1
  build_runner: ^2.4.9
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"

flutter:

  
  uses-material-design: true